baseURL = 'https://artikoplaster.us/'
languageCode = 'en-us'
title = 'Artiko - Venetian Plaster Specialists'

[params]
  description = 'Beautiful, high-quality Venetian plaster finishes in New York and beyond'
  phone = '917-664-9684'
  email = 'info@artikoplaster.us'
  linkedin = 'https://www.linkedin.com/company/artiko_venetaion'
  instagram = 'https://www.instagram.com/artiko_venetian/'
  
[menu]
  [[menu.main]]
    name = 'Services'
    url = '/#services'
    weight = 1
  [[menu.main]]
    name = 'Gallery'
    url = '/gallery'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/#about'
    weight = 3
  [[menu.main]]
    name = 'Contact'
    url = '/#contact'
    weight = 4
